version: 0.2
phases:
    install:
        commands:
            - echo "Python has some SSL issues in this version so we force an upgrade which doesn't fix everything; don't be alarmed by the warnings."
            - sudo -i pip install --upgrade requests            
    build:
        commands:
            - echo "S3 Upload Beginning"
            - python -V
            - export ACCID=$(aws sts get-caller-identity --query 'Account' | tr -d '"')
            - aws s3 sync . s3://servicesatalog-deployedtemplates-$ACCID/ --delete --exclude "*" --include "*.json" --include "*.yml"
            - echo "S3 Upload Complete, updating cloudformation now..."
            - /bin/bash codepipeline/run-pipelineupdate.sh
            -/bin/bash codepipeline/run-cloudformationupdate.sh
    post_build:
        commands:
            - echo "Deploy complete"
